version: '3'

services:
  backend:
    container_name: "backend"
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 3000:3000
    command:  bash -c "cd /app && npm install && npm run dev"
    #links: 
      #- db

  #db:
    #container_name: "db"
    #image: mongo:3.2-jessie
    #restart: always
    #ports:
        #- 27017:27017
    #environment: 
        #MONGO_INITDB_ROOT_USERNAME: root
        #MONGO_INITDB_ROOT_PASSWORD: secret
